language: python
python:
  - 3.7
before_install:
  - pip install -U pip
install:
  - pip install ".[test]" .
script: nosetests --with-coverage
deploy:
  provider: pypi
  user: __token__
  password:
    secure: czyek1fUkBb4wxT2YAUXU2ckvTieeewqGdq8qxQ1tT63qMGgwtmXioNSFW/KLYhq6vFNjyiRSLq34wJzGw0+PnIiU3NTE0vPAz7eFzhiLlL2uMKYsv88K8XldTqeEzF7sueUfNtDmvG9JCetuRbQECyn4PNjE+yDIC2oHIvjIH0Zp+zE1doAFAL0kjqB5Na9HA2D/GVCAcQi7lHuTm4KWUPYtdIeLaChvPjQpAWy8o4yJn/W1YIMtnACkNZQSGCoLed3LKVnZ+EkDek2HFsUwSvRW8Cbv5NA/JG7dKhMEhXMg785LVxYcur7ds1QWsaOD+CrVYS7Is1R5BFVdImrBhdiMuHtyPpt+XlgWYsog6kdpv7JT2CnQDe1f6yuuNS0ptYbqFaIIdSdtQTVAZlA79HZfXqXo0cls687mrIezr0aiqf1Tj+UGV7FWiWL8VXbNqUPhBF/xfQMjBw18sWA+LUYFmRwLnb0SJPXkZMka8vPcgafhSDoz1SdEu0SPkyp1VcsL2RvCX8m4w+IgHcGEbExCoRz6NdP1NRdVnPBoknOAANqifkzBikVz960UriPkx1LCtQ3EUWpHsTWAHgvrBlr8clDODBzzhiKjqV3Kyq7sP/TR6LiKmdAcGihTWzsZSoQmlINtwHC1hFpK41HcXh1IFaUc7nZLtlyIEo5Dr8=
after_success:
  - codecov
